version: '3.7'
services:
  mysql:
    image: mysql:8-debian
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=vue
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./.docker/data/mysql:/var/lib/mysql
    ports:
      - "3307:3306"

  php:
    platform: linux/x86_64
    build: ./.docker/php
    ports: ['9001:9000']
    volumes: ['${CI_PROJECT_DIR:-.}:/var/www']

  nginx:
    build: ./.docker/nginx
    ports: ['88:80']
    volumes: ['${CI_PROJECT_DIR:-.}:/var/www']